apiVersion: apps/v1
kind: Deployment
metadata:
  name: ocr-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ocr-frontend
  template:
    metadata:
      labels:
        app: ocr-frontend
    spec:
      containers:
      - name: ocr-frontend
        image: srivamsia11/ocr-frontend:v2
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: ocr-frontend
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 3000
  selector:
    app: ocr-frontend
