apiVersion: apps/v1
kind: Deployment
metadata:
  name: ocr-worker
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ocr-worker
  template:
    metadata:
      labels:
        app: ocr-worker
    spec:
      containers:
      - name: ocr-worker
        image: srivamsia11/ocr-worker:latest
        env:
        - name: MONGO_URL
          #value: "mongodb+srv://andavarapuvamsi3:qISi9R1HeApjKYlJ@dcscproject.puj7i.mongodb.net/"
          value: "mongodb://mongodb-service:27017/ocr_database"
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: "dcscproject-34b356ce3665.json"
        - name: GCS_BUCKET
          value: "dcscprojectb1"
        - name: RABBITMQ_HOST
          value: "rabbitmq"
        volumeMounts:
        # Mount the GCS credentials as a file inside the container
        - name: gcs-credentials
          mountPath: dcscproject-34b356ce3665.json
          subPath: dcscproject-34b356ce3665.json
        # resources:
        #   requests:
        #     memory: "256Mi"
        #     cpu: "500m"
        #   limits:
        #     memory: "512Mi"
        #     cpu: "1000m"
      volumes:
      # Define the volume for GCS credentials
      - name: gcs-credentials
        secret:
          secretName: gcs-secret
